# Generated by Django 5.2.3 on 2025-09-22 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anamneses", "0003_alter_anamnese_dados_entrada_ia_and_more"),
        ("cidadaos", "0003_cidadao_endereco_capturado_automaticamente_and_more"),
        ("saude_dados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoLocalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude_anterior",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "longitude_anterior",
                    models.DecimalField(decimal_places=8, max_digits=11, null=True),
                ),
                ("latitude_nova", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "longitude_nova",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                (
                    "motivo_mudanca",
                    models.CharField(
                        help_text="Motivo da alteração da localização", max_length=200
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_localizacao",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Localização",
                "verbose_name_plural": "Histórico de Localizações",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LocalizacaoSaude",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("endereco_completo", models.CharField(blank=True, max_length=500)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "nivel_risco",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo Risco"),
                            ("medio", "Médio Risco"),
                            ("alto", "Alto Risco"),
                            ("critico", "Crítico"),
                        ],
                        default="baixo",
                        max_length=10,
                    ),
                ),
                (
                    "pontuacao_risco",
                    models.IntegerField(
                        default=0, help_text="Pontuação numérica do risco"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "anamnese",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anamneses.anamnese",
                    ),
                ),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizacoes_saude",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "dados_saude",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_dados.dadossaude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localização de Saúde",
                "verbose_name_plural": "Localizações de Saúde",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RelatorioMedico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_relatorio",
                    models.CharField(
                        choices=[
                            ("triagem", "Triagem Inicial"),
                            ("acompanhamento", "Acompanhamento"),
                            ("emergencia", "Emergência"),
                            ("preventivo", "Preventivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gerado", "Gerado"),
                            ("revisado", "Revisado"),
                            ("aprovado", "Aprovado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="gerado",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo_clinico", models.TextField()),
                ("recomendacoes", models.TextField()),
                ("medicamentos_sugeridos", models.TextField(blank=True)),
                ("exames_solicitados", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("dados_completos", models.JSONField(default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios_medicos",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "localizacao_saude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios",
                        to="geolocation.localizacaosaude",
                    ),
                ),
                (
                    "medico_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Médico",
                "verbose_name_plural": "Relatórios Médicos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
