# Generated by Django 5.2.6 on 2025-09-18 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cidadaos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosAnonimizados",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hash_cidadao", models.CharField(db_index=True, max_length=64)),
                ("faixa_etaria", models.CharField(max_length=20)),
                ("sexo", models.CharField(max_length=1)),
                ("regiao_residencia", models.CharField(max_length=50)),
                ("tem_doenca_cronica", models.BooleanField(null=True)),
                ("categoria_imc", models.CharField(blank=True, max_length=20)),
                ("nivel_risco_geral", models.CharField(blank=True, max_length=20)),
                (
                    "data_anonimizacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("finalidade", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Dados Anonimizados",
                "verbose_name_plural": "Dados Anonimizados",
                "indexes": [
                    models.Index(
                        fields=["faixa_etaria", "sexo"],
                        name="lgpd_dadosa_faixa_e_878f02_idx",
                    ),
                    models.Index(
                        fields=["data_anonimizacao"],
                        name="lgpd_dadosa_data_an_f0cf69_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PoliticaPrivacidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("versao", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                ("data_vigencia", models.DateTimeField()),
                ("ativa", models.BooleanField(default=False)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Política de Privacidade",
                "verbose_name_plural": "Políticas de Privacidade",
                "ordering": ["-data_vigencia"],
            },
        ),
        migrations.CreateModel(
            name="ViolacaoDados",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_violacao",
                    models.CharField(
                        choices=[
                            ("ACESSO_NAO_AUTORIZADO", "Acesso não autorizado"),
                            ("VAZAMENTO_DADOS", "Vazamento de dados"),
                            ("PERDA_DADOS", "Perda de dados"),
                            ("ALTERACAO_NAO_AUTORIZADA", "Alteração não autorizada"),
                            ("TENTATIVA_INVASAO", "Tentativa de invasão"),
                            ("USO_INDEVIDO", "Uso indevido de dados"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField()),
                ("tipos_dados_afetados", models.JSONField(default=list)),
                (
                    "data_deteccao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "data_ocorrencia_estimada",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("acoes_corretivas", models.TextField(blank=True)),
                ("anpd_notificada", models.BooleanField(default=False)),
                ("data_notificacao_anpd", models.DateTimeField(blank=True, null=True)),
                ("cidadaos_notificados", models.BooleanField(default=False)),
                (
                    "data_notificacao_cidadaos",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("resolvida", models.BooleanField(default=False)),
                ("data_resolucao", models.DateTimeField(blank=True, null=True)),
                (
                    "cidadaos_afetados",
                    models.ManyToManyField(
                        blank=True, related_name="violacoes", to="cidadaos.cidadao"
                    ),
                ),
                (
                    "detectado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violacoes_detectadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Violação de Dados",
                "verbose_name_plural": "Violações de Dados",
                "ordering": ["-data_deteccao"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaAcesso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("ACESSO_DADOS", "Acesso aos dados"),
                            ("MODIFICACAO_DADOS", "Modificação de dados"),
                            ("EXCLUSAO_DADOS", "Exclusão de dados"),
                            ("ANONIMIZACAO_DADOS", "Anonimização de dados"),
                            ("EXPORTACAO_DADOS", "Exportação de dados"),
                            ("CONSENTIMENTO_DADO", "Consentimento concedido"),
                            ("CONSENTIMENTO_REVOGADO", "Consentimento revogado"),
                            ("VIOLACAO_DADOS", "Violação de dados detectada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detalhes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("url_acessada", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos_auditoria",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acessos_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de Acesso",
                "verbose_name_plural": "Auditorias de Acesso",
                "indexes": [
                    models.Index(
                        fields=["cidadao", "timestamp"],
                        name="lgpd_audito_cidadao_684900_idx",
                    ),
                    models.Index(
                        fields=["usuario", "timestamp"],
                        name="lgpd_audito_usuario_d8b3c9_idx",
                    ),
                    models.Index(
                        fields=["tipo_acao", "timestamp"],
                        name="lgpd_audito_tipo_ac_4b287b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentimentoLGPD",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            (
                                "ATENDIMENTO_MEDICO",
                                "Atendimento médico e cuidados de saúde",
                            ),
                            (
                                "PESQUISA_CIENTIFICA",
                                "Pesquisa científica em saúde pública",
                            ),
                            (
                                "ESTATISTICAS_PUBLICAS",
                                "Estatísticas e análises de saúde pública",
                            ),
                            (
                                "INTELIGENCIA_ARTIFICIAL",
                                "Processamento por IA para diagnóstico",
                            ),
                            (
                                "COMUNICACAO_EMERGENCIA",
                                "Comunicação em casos de emergência",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("consentido", models.BooleanField(default=True)),
                ("token_consentimento", models.CharField(max_length=64, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "data_consentimento",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("valido_ate", models.DateTimeField()),
                ("data_revogacao", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consentimentos",
                        to="cidadaos.cidadao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentimento LGPD",
                "verbose_name_plural": "Consentimentos LGPD",
                "indexes": [
                    models.Index(
                        fields=["cidadao", "finalidade"],
                        name="lgpd_consen_cidadao_b4e437_idx",
                    ),
                    models.Index(
                        fields=["valido_ate"], name="lgpd_consen_valido__cc014d_idx"
                    ),
                ],
                "unique_together": {("cidadao", "finalidade")},
            },
        ),
    ]
