# Generated by Django 5.2.6 on 2025-09-18 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstatisticaTempoReal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_cidadaos_cadastrados", models.PositiveIntegerField(default=0)),
                ("total_atendimentos_hoje", models.PositiveIntegerField(default=0)),
                ("total_atendimentos_semana", models.PositiveIntegerField(default=0)),
                ("total_anamneses_pendentes", models.PositiveIntegerField(default=0)),
                ("casos_risco_alto_hoje", models.PositiveIntegerField(default=0)),
                ("casos_risco_medio_hoje", models.PositiveIntegerField(default=0)),
                ("alertas_nao_resolvidos", models.PositiveIntegerField(default=0)),
                (
                    "tempo_medio_anamnese",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tempo médio para gerar anamnese (segundos)",
                        max_digits=8,
                    ),
                ),
                (
                    "taxa_sucesso_ia",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Taxa de sucesso da IA (%)",
                        max_digits=5,
                    ),
                ),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estatística em Tempo Real",
                "verbose_name_plural": "Estatísticas em Tempo Real",
            },
        ),
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("secretario", "Secretário de Saúde"),
                            ("coordenador", "Coordenador"),
                            ("agente", "Agente de Saúde"),
                            ("medico", "Médico Revisor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "widgets_ativos",
                    models.JSONField(
                        default=list, help_text="Lista de widgets ativos no dashboard"
                    ),
                ),
                (
                    "filtros_padrao",
                    models.JSONField(
                        default=dict, help_text="Filtros padrão aplicados no dashboard"
                    ),
                ),
                ("notificar_risco_alto", models.BooleanField(default=True)),
                ("notificar_novos_casos", models.BooleanField(default=True)),
                ("notificar_relatorios", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Dashboard",
                "verbose_name_plural": "Configurações do Dashboard",
            },
        ),
        migrations.CreateModel(
            name="ExportacaoDados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_dados",
                    models.CharField(
                        help_text="Tipo de dados exportados", max_length=50
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "filtros_aplicados",
                    models.JSONField(help_text="Filtros aplicados na exportação"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="exports/"),
                ),
                ("erro_detalhes", models.TextField(blank=True)),
                ("total_registros", models.PositiveIntegerField(default=0)),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(
                        default=0, help_text="Tamanho em bytes"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação de Dados",
                "verbose_name_plural": "Exportações de Dados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RelatorioSaude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensal", "Relatório Mensal"),
                            ("trimestral", "Relatório Trimestral"),
                            ("anual", "Relatório Anual"),
                            ("especial", "Relatório Especial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fim", models.DateField()),
                ("total_atendimentos", models.PositiveIntegerField(default=0)),
                ("total_cidadaos", models.PositiveIntegerField(default=0)),
                ("casos_risco_alto", models.PositiveIntegerField(default=0)),
                ("casos_risco_medio", models.PositiveIntegerField(default=0)),
                ("casos_risco_baixo", models.PositiveIntegerField(default=0)),
                (
                    "tendencias_saude",
                    models.JSONField(
                        blank=True,
                        help_text="Tendências identificadas pela IA",
                        null=True,
                    ),
                ),
                (
                    "clusters_doencas",
                    models.JSONField(
                        blank=True,
                        help_text="Clusters de doenças identificados",
                        null=True,
                    ),
                ),
                (
                    "hotspots_geograficos",
                    models.JSONField(
                        blank=True,
                        help_text="Hot-spots geográficos de problemas de saúde",
                        null=True,
                    ),
                ),
                (
                    "recomendacoes_ia",
                    models.TextField(
                        blank=True,
                        help_text="Recomendações da IA para políticas públicas",
                    ),
                ),
                ("distribuicao_idade", models.JSONField(blank=True, null=True)),
                ("distribuicao_sexo", models.JSONField(blank=True, null=True)),
                ("distribuicao_geografica", models.JSONField(blank=True, null=True)),
                ("sintomas_mais_comuns", models.JSONField(blank=True, null=True)),
                ("diagnosticos_frequentes", models.JSONField(blank=True, null=True)),
                ("medicamentos_mais_usados", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "gerado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Saúde",
                "verbose_name_plural": "Relatórios de Saúde",
                "ordering": ["-criado_em"],
            },
        ),
    ]
