# Generated by Django 5.2.3 on 2025-09-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cidadaos", "0003_cidadao_endereco_capturado_automaticamente_and_more"),
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitaAgendada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_visita",
                    models.DateTimeField(
                        help_text="Data e hora agendada para a visita"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("retorno_exame", "Retorno de Exame"),
                            ("avaliacao_sintomas", "Avaliação de Sintomas"),
                            (
                                "acompanhamento_comorbidades",
                                "Acompanhamento de Comorbidades",
                            ),
                            ("primeira_visita", "Primeira Visita"),
                            ("revisao_anamnese", "Revisão de Anamnese"),
                            ("medicacao", "Controle de Medicação"),
                            ("preventiva", "Consulta Preventiva"),
                            ("emergencia", "Situação de Emergência"),
                            ("outros", "Outros"),
                        ],
                        help_text="Motivo principal da visita",
                        max_length=30,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, help_text="Observações adicionais sobre a visita"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("confirmada", "Confirmada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("reagendada", "Reagendada"),
                        ],
                        default="agendada",
                        help_text="Status atual da visita",
                        max_length=15,
                    ),
                ),
                (
                    "data_realizacao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora real da visita (quando realizada)",
                        null=True,
                    ),
                ),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duração da visita em minutos", null=True
                    ),
                ),
                (
                    "relatorio_visita",
                    models.TextField(
                        blank=True, help_text="Relatório da visita realizada"
                    ),
                ),
                (
                    "notificacao_enviada",
                    models.BooleanField(
                        default=False,
                        help_text="Se já foi enviada notificação para o cidadão",
                    ),
                ),
                (
                    "lembrete_agente",
                    models.BooleanField(
                        default=True, help_text="Se deve enviar lembrete para o agente"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "agente",
                    models.ForeignKey(
                        help_text="Agente de saúde responsável pela visita",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas_agendadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cidadao",
                    models.ForeignKey(
                        help_text="Cidadão que receberá a visita",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas_agendadas",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou o agendamento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita Agendada",
                "verbose_name_plural": "Visitas Agendadas",
                "ordering": ["data_visita"],
                "indexes": [
                    models.Index(
                        fields=["data_visita", "status"],
                        name="dashboard_v_data_vi_04cf01_idx",
                    ),
                    models.Index(
                        fields=["cidadao", "status"],
                        name="dashboard_v_cidadao_785848_idx",
                    ),
                    models.Index(
                        fields=["agente", "data_visita"],
                        name="dashboard_v_agente__dddbb1_idx",
                    ),
                ],
            },
        ),
    ]
