# Generated by Django 5.2.3 on 2025-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_visitaagendada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do vídeo de treinamento", max_length=200
                    ),
                ),
                (
                    "descricao",
                    models.TextField(help_text="Descrição do conteúdo do treinamento"),
                ),
                (
                    "url_video",
                    models.URLField(
                        help_text="Link do vídeo no YouTube (ex: https://www.youtube.com/watch?v=VIDEO_ID)"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        help_text="Data em que o treinamento foi disponibilizado"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o vídeo está visível para os agentes",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Treinamento",
                "verbose_name_plural": "Treinamentos",
                "ordering": ["-data_publicacao"],
            },
        ),
    ]
