# Generated by Django 5.2.3 on 2025-09-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_add_treinamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("procedimentos", "Procedimentos de Saúde"),
                    ("prevencao", "Prevenção e Cuidados"),
                    ("emergencia", "Atendimento de Emergência"),
                    ("doencas_cronicas", "Doenças Crônicas"),
                    ("saude_mental", "Saúde Mental"),
                    ("vacinacao", "Vacinação"),
                    ("higiene", "Higiene e Sanitização"),
                    ("comunicacao", "Comunicação com Pacientes"),
                    ("lgpd", "LGPD e Privacidade"),
                    ("outros", "Outros"),
                ],
                default="outros",
                help_text="Categoria do treinamento para organização",
                max_length=20,
            ),
        ),
    ]
