# Generated by Django 5.2.3 on 2025-09-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_treinamento_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da categoria (ex: Procedimentos de Saúde)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da categoria",
                        null=True,
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição da categoria (menor número aparece primeiro)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria de Treinamento",
                "verbose_name_plural": "Categorias de Treinamento",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterField(
            model_name="treinamento",
            name="categoria",
            field=models.ForeignKey(
                help_text="Categoria do treinamento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treinamentos",
                to="dashboard.categoriatreinamento",
            ),
        ),
    ]
