# Generated by Django 5.2.6 on 2025-09-18 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cidadaos", "0001_initial"),
        ("saude_dados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anamnese",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resumo_anamnese",
                    models.TextField(
                        help_text="Anamnese resumida (máximo 200 palavras)"
                    ),
                ),
                (
                    "hipoteses_diagnosticas",
                    models.JSONField(
                        help_text="Lista de hipóteses diagnósticas ordenadas por probabilidade"
                    ),
                ),
                (
                    "triagem_risco",
                    models.CharField(
                        choices=[
                            ("baixo", "Risco Baixo"),
                            ("medio", "Risco Médio"),
                            ("alto", "Risco Alto"),
                            ("critico", "Risco Crítico"),
                        ],
                        help_text="Classificação de risco automática",
                        max_length=10,
                    ),
                ),
                (
                    "recomendacoes",
                    models.TextField(help_text="Recomendações iniciais da IA"),
                ),
                (
                    "modelo_ia_usado",
                    models.CharField(
                        default="gpt-3.5-turbo",
                        help_text="Modelo de IA utilizado",
                        max_length=50,
                    ),
                ),
                (
                    "confianca_ia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nível de confiança da IA (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "dados_entrada_ia",
                    models.JSONField(
                        help_text="Dados enviados para a IA (para auditoria)"
                    ),
                ),
                (
                    "resposta_completa_ia",
                    models.JSONField(help_text="Resposta completa da IA"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente Revisão"),
                            ("aprovada", "Aprovada"),
                            ("rejeitada", "Rejeitada"),
                            ("revisao", "Em Revisão"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("data_revisao", models.DateTimeField(blank=True, null=True)),
                (
                    "comentarios_revisao",
                    models.TextField(
                        blank=True, help_text="Comentários do revisor médico"
                    ),
                ),
                (
                    "resumo_final",
                    models.TextField(
                        blank=True, help_text="Resumo final após revisão médica"
                    ),
                ),
                (
                    "diagnostico_final",
                    models.TextField(
                        blank=True, help_text="Diagnóstico final após revisão"
                    ),
                ),
                (
                    "recomendacoes_finais",
                    models.TextField(
                        blank=True, help_text="Recomendações finais após revisão"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("enviado_secretaria", models.BooleanField(default=False)),
                ("data_envio_secretaria", models.DateTimeField(blank=True, null=True)),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anamneses",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "dados_saude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anamneses",
                        to="saude_dados.dadossaude",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anamneses_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anamnese",
                "verbose_name_plural": "Anamneses",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AlertaSaude",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("risco_alto", "Risco Alto Detectado"),
                            ("sintoma_grave", "Sintoma Grave"),
                            ("medicacao", "Alerta de Medicação"),
                            ("acompanhamento", "Necessita Acompanhamento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("acao_recomendada", models.TextField()),
                ("prazo_acao", models.DateTimeField(blank=True, null=True)),
                ("visualizado", models.BooleanField(default=False)),
                ("resolvido", models.BooleanField(default=False)),
                ("data_resolucao", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anamnese",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="anamneses.anamnese",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Saúde",
                "verbose_name_plural": "Alertas de Saúde",
                "ordering": ["-prioridade", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoriaIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("anamnese", "Geração de Anamnese"),
                            ("triagem", "Triagem de Risco"),
                            ("extracao", "Extração de Dados"),
                            ("agregacao", "Agregação de Dados"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modelo_ia", models.CharField(max_length=50)),
                ("prompt_enviado", models.TextField()),
                ("dados_entrada", models.JSONField()),
                ("resposta_ia", models.JSONField()),
                ("tempo_processamento", models.DurationField()),
                ("sucesso", models.BooleanField()),
                ("erro_detalhes", models.TextField(blank=True)),
                (
                    "tokens_utilizados",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "custo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("dados_anonimizados", models.BooleanField(default=False)),
                ("ip_origem", models.GenericIPAddressField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "anamnese",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anamneses.anamnese",
                    ),
                ),
                (
                    "cidadao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria IA",
                "verbose_name_plural": "Logs de Auditoria IA",
                "ordering": ["-criado_em"],
            },
        ),
    ]
