# Generated by Django 5.2.6 on 2025-09-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anamneses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anamnese",
            name="diagnostico_clinico",
            field=models.TextField(
                blank=True, help_text="Diagnóstico clínico principal gerado pela IA"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="diagnostico_diferencial",
            field=models.JSONField(
                default=list, help_text="Lista de diagnósticos diferenciais"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="exames_complementares",
            field=models.JSONField(
                default=list, help_text="Exames recomendados pela IA"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="prognose",
            field=models.TextField(
                blank=True, help_text="Prognóstico do caso gerado pela IA"
            ),
        ),
    ]
