# Generated by Django 5.2.3 on 2025-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anamneses", "0002_anamnese_diagnostico_clinico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anamnese",
            name="dados_entrada_ia",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dados enviados para a IA (para auditoria)",
            ),
        ),
        migrations.AlterField(
            model_name="anamnese",
            name="hipoteses_diagnosticas",
            field=models.JSONField(
                default=list,
                help_text="Lista de hipóteses diagnósticas ordenadas por probabilidade",
            ),
        ),
        migrations.AlterField(
            model_name="anamnese",
            name="resposta_completa_ia",
            field=models.JSONField(
                blank=True, default=dict, help_text="Resposta completa da IA"
            ),
        ),
    ]
