# Generated by Django 5.2.6 on 2025-09-18 00:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidadao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do cidadão", max_length=200
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="CPF no formato 000.000.000-00",
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato 000.000.000-00",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("data_nascimento", models.DateField(help_text="Data de nascimento")),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("S", "Solteiro(a)"),
                            ("C", "Casado(a)"),
                            ("D", "Divorciado(a)"),
                            ("V", "Viúvo(a)"),
                            ("U", "União Estável"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Telefone no formato (00) 00000-0000",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefone deve estar no formato (00) 00000-0000",
                                regex="^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "endereco",
                    models.CharField(help_text="Endereço completo", max_length=200),
                ),
                (
                    "cep",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve estar no formato 00000-000",
                                regex="^\\d{5}-\\d{3}$",
                            )
                        ],
                    ),
                ),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("profissao", models.CharField(blank=True, max_length=100)),
                (
                    "renda_familiar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Renda familiar em reais",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("possui_plano_saude", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cidadão",
                "verbose_name_plural": "Cidadãos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ContatoEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("parentesco", models.CharField(max_length=50)),
                ("telefone", models.CharField(max_length=15)),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos_emergencia",
                        to="cidadaos.cidadao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato de Emergência",
                "verbose_name_plural": "Contatos de Emergência",
            },
        ),
    ]
