# Generated by Django 5.2.3 on 2025-09-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cidadaos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cidadao",
            name="alergias_conhecidas",
            field=models.TextField(blank=True, help_text="Alergias conhecidas"),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="cirurgias_anteriores",
            field=models.TextField(
                blank=True, help_text="Cirurgias realizadas anteriormente"
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="medicamentos_continuo",
            field=models.TextField(
                blank=True, help_text="Medicamentos de uso contínuo"
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="possui_asma",
            field=models.BooleanField(default=False, help_text="Possui asma"),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="possui_depressao",
            field=models.BooleanField(
                default=False, help_text="Possui depressão ou ansiedade"
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="possui_diabetes",
            field=models.BooleanField(
                default=False, help_text="Possui diabetes mellitus"
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="possui_doenca_cardiaca",
            field=models.BooleanField(
                default=False, help_text="Possui doença cardíaca"
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="possui_doenca_renal",
            field=models.BooleanField(default=False, help_text="Possui doença renal"),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="possui_hipertensao",
            field=models.BooleanField(
                default=False, help_text="Possui hipertensão arterial"
            ),
        ),
    ]
