# Generated by Django 5.2.3 on 2025-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cidadaos", "0002_cidadao_alergias_conhecidas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cidadao",
            name="endereco_capturado_automaticamente",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o endereço foi obtido via geolocalização automática",
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Latitude da localização do cidadão",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cidadao",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Longitude da localização do cidadão",
                max_digits=11,
                null=True,
            ),
        ),
    ]
